#  Copyright (c) 2026 TheMukeshDev
#  Licensed under the GNU AGPL v3.0: https://www.gnu.org/licenses/agpl-3.0.html
#  Part of the MelodyForgeBot project. All rights reserved where applicable.

from pytdbot import Client, types

from src.core import Filter

__mod_name__ = "Fonts"
__help__ = """
<b>Font Commands:</b>

• <code>/font [text]</code> — Convert text to various Unicode font styles
• <code>/fonts</code> — List available font styles
"""

FONT_MAPPINGS = {
    "𝐁𝐨𝐥𝐝": {
        "a": "𝐚",
        "b": "𝐛",
        "c": "𝐜",
        "d": "𝐝",
        "e": "𝐞",
        "f": "𝐟",
        "g": "𝐠",
        "h": "𝐡",
        "i": "𝐢",
        "j": "𝐣",
        "k": "𝐤",
        "l": "𝐥",
        "m": "𝐦",
        "n": "𝐧",
        "o": "𝐨",
        "p": "𝐩",
        "q": "𝐪",
        "r": "𝐫",
        "s": "𝐬",
        "t": "𝐭",
        "u": "𝐮",
        "v": "𝐯",
        "w": "𝐰",
        "x": "𝐱",
        "y": "𝐲",
        "z": "𝐳",
        "A": "𝐀",
        "B": "𝐁",
        "C": "𝐂",
        "D": "𝐃",
        "E": "𝐄",
        "F": "𝐅",
        "G": "𝐆",
        "H": "𝐇",
        "I": "𝐈",
        "J": "𝐉",
        "K": "𝐊",
        "L": "𝐋",
        "M": "𝐌",
        "N": "𝐍",
        "O": "𝐎",
        "P": "𝐏",
        "Q": "𝐐",
        "R": "𝐑",
        "S": "𝐒",
        "T": "𝐓",
        "U": "𝐔",
        "V": "𝐕",
        "W": "𝐖",
        "X": "𝐗",
        "Y": "𝐘",
        "Z": "𝐙",
    },
    "𝘐𝘵𝘢𝘭𝘪𝘤": {
        "a": "𝘢",
        "b": "𝘣",
        "c": "𝘤",
        "d": "𝘥",
        "e": "𝘦",
        "f": "𝘧",
        "g": "𝘨",
        "h": "𝘩",
        "i": "𝘪",
        "j": "𝘫",
        "k": "𝘬",
        "l": "𝘭",
        "m": "𝘮",
        "n": "𝘯",
        "o": "𝘰",
        "p": "𝘱",
        "q": "𝘲",
        "r": "𝘳",
        "s": "𝘴",
        "t": "𝘵",
        "u": "𝘶",
        "v": "𝘷",
        "w": "𝘸",
        "x": "𝘹",
        "y": "𝘺",
        "z": "𝘻",
        "A": "𝘈",
        "B": "𝘉",
        "C": "𝘊",
        "D": "𝘋",
        "E": "𝘌",
        "F": "𝘍",
        "G": "𝘎",
        "H": "𝘏",
        "I": "𝘐",
        "J": "𝘑",
        "K": "𝘒",
        "L": "𝘓",
        "M": "𝘔",
        "N": "𝘕",
        "O": "𝘖",
        "P": "𝘗",
        "Q": "𝘘",
        "R": "𝘙",
        "S": "𝘚",
        "T": "𝘛",
        "U": "𝘜",
        "V": "𝘝",
        "W": "𝘞",
        "X": "𝘟",
        "Y": "𝘠",
        "Z": "𝘡",
    },
    "𝔉𝔯𝔞𝔨𝔱𝔲𝔯": {
        "a": "𝔞",
        "b": "𝔟",
        "c": "𝔠",
        "d": "𝔡",
        "e": "𝔢",
        "f": "𝔣",
        "g": "𝔤",
        "h": "𝔥",
        "i": "𝔦",
        "j": "𝔧",
        "k": "𝔨",
        "l": "𝔩",
        "m": "𝔪",
        "n": "𝔫",
        "o": "𝔬",
        "p": "𝔭",
        "q": "𝔮",
        "r": "𝔯",
        "s": "𝔰",
        "t": "𝔱",
        "u": "𝔲",
        "v": "𝔳",
        "w": "𝔴",
        "x": "𝔵",
        "y": "𝔶",
        "z": "𝔷",
        "A": "𝔄",
        "B": "𝔅",
        "C": "ℭ",
        "D": "𝔇",
        "E": "𝔈",
        "F": "𝔉",
        "G": "𝔊",
        "H": "ℌ",
        "I": "ℑ",
        "J": "𝔍",
        "K": "𝔎",
        "L": "𝔏",
        "M": "𝔐",
        "N": "𝔑",
        "O": "𝔒",
        "P": "𝔓",
        "Q": "𝔔",
        "R": "ℜ",
        "S": "𝔖",
        "T": "𝔗",
        "U": "𝔘",
        "V": "𝔙",
        "W": "𝔚",
        "X": "𝔛",
        "Y": "𝔜",
        "Z": "ℨ",
    },
    "됬된": {
        "a": "ⓐ",
        "b": "ⓑ",
        "c": "ⓒ",
        "d": "ⓓ",
        "e": "ⓔ",
        "f": "ⓕ",
        "g": "ⓖ",
        "h": "ⓗ",
        "i": "ⓘ",
        "j": "ⓙ",
        "k": "ⓚ",
        "l": "ⓛ",
        "m": "ⓜ",
        "n": "ⓝ",
        "o": "ⓞ",
        "p": "ⓟ",
        "q": "ⓠ",
        "r": "ⓡ",
        "s": "ⓢ",
        "t": "ⓣ",
        "u": "ⓤ",
        "v": "ⓥ",
        "w": "ⓦ",
        "x": "ⓧ",
        "y": "ⓨ",
        "z": "ⓩ",
        "A": "Ⓐ",
        "B": "Ⓑ",
        "C": "Ⓒ",
        "D": "Ⓓ",
        "E": "Ⓔ",
        "F": "Ⓕ",
        "G": "Ⓖ",
        "H": "Ⓗ",
        "I": "Ⓘ",
        "J": "Ⓙ",
        "K": "Ⓚ",
        "L": "Ⓛ",
        "M": "Ⓜ",
        "N": "Ⓝ",
        "O": "Ⓞ",
        "P": "Ⓟ",
        "Q": "Ⓠ",
        "R": "Ⓡ",
        "S": "Ⓢ",
        "T": "Ⓣ",
        "U": "Ⓤ",
        "V": "Ⓥ",
        "W": "Ⓦ",
        "X": "Ⓧ",
        "Y": "Ⓨ",
        "Z": "Ⓩ",
    },
    "Ｓｑｕａｒｅ": {
        "a": "ａ",
        "b": "ｂ",
        "c": "ｃ",
        "d": "ｄ",
        "e": "ｅ",
        "f": "ｆ",
        "g": "ｇ",
        "h": "ｈ",
        "i": "ｉ",
        "j": "ｊ",
        "k": "ｋ",
        "l": "ｌ",
        "m": "ｍ",
        "n": "ｎ",
        "o": "ｏ",
        "p": "ｐ",
        "q": "ｑ",
        "r": "ｒ",
        "s": "ｓ",
        "t": "ｔ",
        "u": "ｕ",
        "v": "ｖ",
        "w": "ｗ",
        "x": "ｘ",
        "y": "ｙ",
        "z": "ｚ",
        "A": "Ａ",
        "B": "Ｂ",
        "C": "Ｃ",
        "D": "Ｄ",
        "E": "Ｅ",
        "F": "Ｆ",
        "G": "Ｇ",
        "H": "Ｈ",
        "I": "Ｉ",
        "J": "Ｊ",
        "K": "Ｋ",
        "L": "Ｌ",
        "M": "Ｍ",
        "N": "Ｎ",
        "O": "Ｏ",
        "P": "Ｐ",
        "Q": "Ｑ",
        "R": "Ｒ",
        "S": "Ｓ",
        "T": "Ｔ",
        "U": "Ｕ",
        "V": "Ｖ",
        "W": "Ｗ",
        "X": "Ｘ",
        "Y": "Ｙ",
        "Z": "Ｚ",
    },
    "Ⓑⓤⓑⓑⓛⓔ": {
        "a": "ⓐ",
        "b": "ⓑ",
        "c": "ⓒ",
        "d": "ⓓ",
        "e": "ⓔ",
        "f": "ⓕ",
        "g": "ⓖ",
        "h": "ⓗ",
        "i": "ⓘ",
        "j": "ⓙ",
        "k": "ⓚ",
        "l": "ⓛ",
        "m": "ⓜ",
        "n": "ⓝ",
        "o": "ⓞ",
        "p": "ⓟ",
        "q": "ⓠ",
        "r": "ⓡ",
        "s": "ⓢ",
        "t": "ⓣ",
        "u": "ⓤ",
        "v": "ⓥ",
        "w": "ⓦ",
        "x": "ⓧ",
        "y": "ⓨ",
        "z": "ⓩ",
        "A": "Ⓐ",
        "B": "Ⓑ",
        "C": "Ⓒ",
        "D": "Ⓓ",
        "E": "Ⓔ",
        "F": "Ⓕ",
        "G": "Ⓖ",
        "H": "Ⓗ",
        "I": "Ⓘ",
        "J": "Ⓙ",
        "K": "Ⓚ",
        "L": "Ⓛ",
        "M": "Ⓜ",
        "N": "Ⓝ",
        "O": "Ⓞ",
        "P": "Ⓟ",
        "Q": "Ⓠ",
        "R": "Ⓡ",
        "S": "Ⓢ",
        "T": "Ⓣ",
        "U": "Ⓤ",
        "V": "Ⓥ",
        "W": "Ⓦ",
        "X": "Ⓧ",
        "Y": "Ⓨ",
        "Z": "Ⓩ",
    },
    "Ｔｈｉｎ": {
        "a": "𝑎",
        "b": "𝑏",
        "c": "𝑐",
        "d": "𝑑",
        "e": "𝑒",
        "f": "𝑓",
        "g": "𝑔",
        "h": "ℎ",
        "i": "𝑖",
        "j": "𝑗",
        "k": "𝑘",
        "l": "𝑙",
        "m": "𝑚",
        "n": "𝑛",
        "o": "𝑜",
        "p": "𝑝",
        "q": "𝑞",
        "r": "𝑟",
        "s": "𝑠",
        "t": "𝑡",
        "u": "𝑢",
        "v": "𝑣",
        "w": "𝑤",
        "x": "𝑥",
        "y": "𝑦",
        "z": "𝑧",
        "A": "𝐴",
        "B": "𝐵",
        "C": "𝐶",
        "D": "𝐷",
        "E": "𝐸",
        "F": "𝐹",
        "G": "𝐺",
        "H": "𝐻",
        "I": "𝐼",
        "J": "𝐽",
        "K": "𝐾",
        "L": "𝐿",
        "M": "𝑀",
        "N": "𝑁",
        "O": "𝑂",
        "P": "𝑃",
        "Q": "𝑄",
        "R": "𝑅",
        "S": "𝑆",
        "T": "𝑇",
        "U": "𝑈",
        "V": "𝑉",
        "W": "𝑊",
        "X": "𝑋",
        "Y": "𝑌",
        "Z": "𝑍",
    },
}


def _convert_text(text: str, mapping: dict) -> str:
    result = ""
    for char in text:
        if char in mapping:
            result += mapping[char]
        else:
            result += char
    return result


@Client.on_message(filters=Filter.command("font"))
async def font_cmd(c: Client, message: types.Message) -> None:
    text = message.text or ""
    parts = text.split(None, 1)
    if len(parts) < 2:
        reply = await message.reply_text(
            "ℹ️ Please provide text to convert.\nUsage: <code>/font [text]</code>"
        )
        if isinstance(reply, types.Error):
            c.logger.warning(f"font_cmd error: {reply.message}")
        return

    input_text = parts[1]
    response = "<b>🎨 Font Styles:</b>\n\n"

    for name, mapping in FONT_MAPPINGS.items():
        converted = _convert_text(input_text, mapping)
        response += f"<b>{name}:</b>\n<code>{converted}</code>\n\n"

    if len(response) > 4000:
        response = response[:4000]

    reply = await message.reply_text(response)
    if isinstance(reply, types.Error):
        c.logger.warning(f"font_cmd error: {reply.message}")


@Client.on_message(filters=Filter.command("fonts"))
async def fonts_cmd(c: Client, message: types.Message) -> None:
    text = "<b>🎨 Available Font Styles:</b>\n\n"
    for i, name in enumerate(FONT_MAPPINGS.keys(), 1):
        text += f"{i}. <b>{name}</b>\n"
    text += "\n💡 Use <code>/font [text]</code> to convert your text."

    reply = await message.reply_text(text)
    if isinstance(reply, types.Error):
        c.logger.warning(f"fonts_cmd error: {reply.message}")
